## Objective: Learning to solve basic Python problems

Prerequisites: Module 1 listed @ https://www.appliedaicourse.com/course/11/Applied-Machine-learning-course - SQL

Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [1]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
A1 = np.random.rand(5,4) # read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[0.06097725 0.51384534 0.18322399 0.45430321]
 [0.28492164 0.55686539 0.6918515  0.94162756]
 [0.49962967 0.08302578 0.76424443 0.84545005]
 [0.02147335 0.68672843 0.28507371 0.50399492]
 [0.58968126 0.27365276 0.99417526 0.84913075]]
(5, 4)


In [2]:
print(A1.shape()); #COMMON-ERROR

TypeError: 'tuple' object is not callable

In [3]:
print(A1.type); # COMMON-ERROR

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [4]:
print(type(A1));

<class 'numpy.ndarray'>


In [5]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [6]:
# Create random Matrix A2
A2 = np.random.rand(5,4);

print(A2);

[[0.30323807 0.14951422 0.66738195 0.72299737]
 [0.40744433 0.99233876 0.60560385 0.09085748]
 [0.7226854  0.5304838  0.13601094 0.00344747]
 [0.0749969  0.63684057 0.75698982 0.34433932]
 [0.06597967 0.68997706 0.64418274 0.8056797 ]]


In [7]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A2[2,3]);


0.003447470585022483


In [8]:
print(A1(2,3)); #COMMON_ERROR

TypeError: 'numpy.ndarray' object is not callable

In [9]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[0.36421532 0.66335956 0.85060594 1.17730058]
 [0.69236597 1.54920415 1.29745535 1.03248504]
 [1.22231507 0.61350958 0.90025537 0.84889752]
 [0.09647025 1.32356899 1.04206353 0.84833424]
 [0.65566093 0.96362982 1.638358   1.65481045]]


In [10]:
(r,c) = A1.shape;
print(r,c)

5 4


In [11]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.36421532 0.66335956 0.85060594 1.17730058]
 [0.69236597 1.54920415 1.29745535 1.03248504]
 [1.22231507 0.61350958 0.90025537 0.84889752]
 [0.09647025 1.32356899 1.04206353 0.84833424]
 [0.65566093 0.96362982 1.638358   1.65481045]]


In [12]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros(5,4); # COMMON-ERROR

TypeError: data type not understood

In [13]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html
B = np.zeros((5,4))

for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.36421532 0.66335956 0.85060594 1.17730058]
 [0.69236597 1.54920415 1.29745535 1.03248504]
 [1.22231507 0.61350958 0.90025537 0.84889752]
 [0.09647025 1.32356899 1.04206353 0.84833424]
 [0.65566093 0.96362982 1.638358   1.65481045]]


In [14]:
# Time Complexity: ?
# Space Complxiety: ?

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************


In [20]:
Matrix3DOne=np.random.rand(3,3,3)
Matrix3DTwo=np.random.rand(3,3,3)

In [28]:
B=Matrix3DOne+Matrix3DTwo
print(B)

[[[0.79357508 1.36406223 1.10554998]
  [1.27627326 0.94537693 0.68074407]
  [1.52049685 0.0607024  0.83274023]]

 [[1.23199063 1.43111067 0.76402661]
  [1.60730764 0.80363449 0.63530391]
  [1.41209763 1.02285481 1.09868394]]

 [[1.3238557  0.29550597 0.61282576]
  [1.04418276 0.98023843 1.15923553]
  [1.20760021 0.47852508 1.32039056]]]


In [37]:
(height,row,coloumn)=Matrix3DOne.shape

OutputMatrix3D=np.zeros((3,3,3))
for i in range(height):
    for j in range(row):
        for k in range(coloumn):
            OutputMatrix3D[i,j,k]=Matrix3DOne[i,j,k]+Matrix3DTwo[i,j,k]
print(OutputMatrix3D)



[[[0.79357508 1.36406223 1.10554998]
  [1.27627326 0.94537693 0.68074407]
  [1.52049685 0.0607024  0.83274023]]

 [[1.23199063 1.43111067 0.76402661]
  [1.60730764 0.80363449 0.63530391]
  [1.41209763 1.02285481 1.09868394]]

 [[1.3238557  0.29550597 0.61282576]
  [1.04418276 0.98023843 1.15923553]
  [1.20760021 0.47852508 1.32039056]]]


### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [1]:
## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = raw_input().split();

print(Cx, Cy, r); # always cross check using print statements

Enter Cx, Cy, r:


NameError: name 'raw_input' is not defined

In [3]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

Cx, Cy, r = map(float,input("Enter Cx, Cy, r:").split());



Enter Cx, Cy, r:.5 .5 1


In [50]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input

#Cx, Cy, r = raw_input("Enter Cx, Cy, r:").split();


1


In [63]:
print(Cx, Cy,r)

('0.0', '0.0', '5.0')


In [4]:
# Input Px, Py

Px, Py = map(float,input("Enter Px, Py:").split())
print(Px, Py);

Enter Px, Py:1 1
1.0 1.0


In [5]:
# Check if P lies in C.
import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

0.7071067811865476
P in C


In [68]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

1.41421356237
P in C


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************


In [18]:
LeftTopx, LeftTopy=map(int,input("enter cordinate").split())
RightBottomx, RightBottomy=map(int,input("Enter Coordinate").split())
x , y =map(int,input("Enter cordinate of the points").split())

enter cordinate2 3
Enter Coordinate4 -3
Enter cordinate of the points3 0


In [19]:
def LiesInRectangle():
    if x>LeftTopx and x< RightBottomx and y< LeftTopy and y> RightBottomy:
        return True
    else:
        return False
LiesInRectangle()

True

### Problem 3: NumPy ndarray manupualtion operations


In [21]:
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
import numpy as np
A = np.random.rand(5,4);
print(A);


[[0.93852103 0.13670652 0.46537869 0.58072256]
 [0.96651618 0.58702392 0.24975164 0.51188471]
 [0.38350744 0.99780188 0.35261138 0.51534223]
 [0.46868673 0.22171345 0.88492723 0.96735462]
 [0.36186399 0.41538074 0.04130059 0.96382569]]


In [71]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))


[0.14807421 0.76465119 0.35072274 0.44772859 0.76310969 0.60355746
 0.39205106 0.55551216 0.52171983 0.14015325 0.07435462 0.84967035
 0.31052941 0.57171621 0.36938534 0.92015166 0.14458459 0.12976042
 0.4790811  0.98251111]


In [72]:
print( np.reshape(A, 20, 'F'))

[0.14807421 0.76310969 0.52171983 0.31052941 0.14458459 0.76465119
 0.60355746 0.14015325 0.57171621 0.12976042 0.35072274 0.39205106
 0.07435462 0.36938534 0.4790811  0.44772859 0.55551216 0.84967035
 0.92015166 0.98251111]


In [22]:
print( np.reshape(A, (4,5), 'C'))

[[0.93852103 0.13670652 0.46537869 0.58072256 0.96651618]
 [0.58702392 0.24975164 0.51188471 0.38350744 0.99780188]
 [0.35261138 0.51534223 0.46868673 0.22171345 0.88492723]
 [0.96735462 0.36186399 0.41538074 0.04130059 0.96382569]]


In [23]:
print( np.reshape(A, (4,-1), 'C'))

[[0.93852103 0.13670652 0.46537869 0.58072256 0.96651618]
 [0.58702392 0.24975164 0.51188471 0.38350744 0.99780188]
 [0.35261138 0.51534223 0.46868673 0.22171345 0.88492723]
 [0.96735462 0.36186399 0.41538074 0.04130059 0.96382569]]


In [24]:
print( np.reshape(A, (-1,5), 'C'))

[[0.93852103 0.13670652 0.46537869 0.58072256 0.96651618]
 [0.58702392 0.24975164 0.51188471 0.38350744 0.99780188]
 [0.35261138 0.51534223 0.46868673 0.22171345 0.88492723]
 [0.96735462 0.36186399 0.41538074 0.04130059 0.96382569]]


In [77]:
print( np.reshape(A, (4,6), 'C'))

ValueError: cannot reshape array of size 20 into shape (4,6)

#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [29]:
MatrixA=np.random.rand(4,5,6)

In [31]:
print(np.reshape(MatrixA,(10,-1),'C'))

[[0.19212536 0.31782518 0.17784451 0.05123483 0.91941877 0.1543749
  0.26863888 0.16116484 0.01891897 0.86680945 0.38195554 0.92726219]
 [0.38889747 0.10524564 0.94902688 0.19975639 0.7127733  0.95770769
  0.12665643 0.99337352 0.72582927 0.16020233 0.65660943 0.98842573]
 [0.15191869 0.45044916 0.80070317 0.66393266 0.62116722 0.52344702
  0.6960153  0.24766144 0.25535179 0.80366667 0.8335868  0.60043179]
 [0.97389962 0.50506737 0.18210434 0.18168115 0.51256453 0.30044728
  0.85244867 0.50739077 0.2029622  0.78488401 0.30007892 0.10352915]
 [0.01357295 0.36430588 0.70432559 0.29359488 0.68430222 0.26324617
  0.86439321 0.02519277 0.36116544 0.52519711 0.46010437 0.85912503]
 [0.56984307 0.99383945 0.97478117 0.61332234 0.69835647 0.3805805
  0.89508232 0.87367806 0.14730512 0.29270615 0.65337171 0.85296791]
 [0.98081195 0.96503066 0.71206224 0.53243354 0.00508648 0.2554397
  0.47252664 0.58554324 0.82632292 0.4810729  0.99952535 0.59087897]
 [0.70047216 0.85592634 0.98323944 0.1127519

In [32]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.0479969  0.20525677 0.30610982 0.76995261]
 [0.53430013 0.16592589 0.75012228 0.28390275]
 [0.38430842 0.15498889 0.32227159 0.13096658]
 [0.99260012 0.64529944 0.1654186  0.61363303]
 [0.14352289 0.08048337 0.72743701 0.72941228]]
[[0.9977111  0.24611976]
 [0.95692203 0.02385896]
 [0.0862994  0.34818749]
 [0.94480579 0.2343302 ]
 [0.91176049 0.04668726]]


In [33]:
# C = [A B]
C = np.hstack((A, B));
print(C)

[[0.0479969  0.20525677 0.30610982 0.76995261 0.9977111  0.24611976]
 [0.53430013 0.16592589 0.75012228 0.28390275 0.95692203 0.02385896]
 [0.38430842 0.15498889 0.32227159 0.13096658 0.0862994  0.34818749]
 [0.99260012 0.64529944 0.1654186  0.61363303 0.94480579 0.2343302 ]
 [0.14352289 0.08048337 0.72743701 0.72941228 0.91176049 0.04668726]]


In [81]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.4543747  0.64690556 0.01325659 0.4005741  0.93198709 0.02293127]
 [0.37270572 0.9229127  0.11746422 0.23759922 0.84602856 0.18276059]
 [0.91889495 0.53198908 0.40542735 0.57103514 0.00741556 0.54525969]
 [0.2562349  0.96441954 0.77128697 0.98914802 0.33630522 0.79257607]
 [0.5388144  0.79256948 0.58861248 0.5072647  0.00361456 0.58644709]]


In [34]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B));
print(C)

[[0.18766276 0.13248549 0.06629369 0.04432297]
 [0.65694053 0.11330921 0.56822603 0.38123356]
 [0.50919349 0.72955678 0.23345748 0.30153398]
 [0.00421076 0.68788476 0.52392274 0.35705819]
 [0.45136803 0.59304164 0.00329296 0.57831357]]
[[0.87036444 0.88303938 0.22897983 0.44810423]
 [0.9482373  0.29335447 0.75612112 0.32078605]
 [0.32101262 0.90242676 0.66129129 0.39241152]
 [0.72123897 0.65556396 0.60654246 0.63093943]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [35]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B)); #Vertical stacking
print(C)

[[0.53224745 0.04200915 0.3075061  0.81741781]
 [0.93015191 0.00447054 0.21871642 0.93589046]
 [0.86329283 0.17649935 0.26076984 0.80148162]
 [0.1872955  0.17122093 0.48835148 0.46468472]
 [0.04939207 0.16189879 0.80074886 0.71084433]]
[[0.93638475 0.62120367 0.11529908 0.59161765]
 [0.51425692 0.39537249 0.34380736 0.20417376]
 [0.87400692 0.60221108 0.95765989 0.9857275 ]
 [0.53091832 0.70690896 0.08669885 0.55407219]]
[[0.53224745 0.04200915 0.3075061  0.81741781]
 [0.93015191 0.00447054 0.21871642 0.93589046]
 [0.86329283 0.17649935 0.26076984 0.80148162]
 [0.1872955  0.17122093 0.48835148 0.46468472]
 [0.04939207 0.16189879 0.80074886 0.71084433]
 [0.93638475 0.62120367 0.11529908 0.59161765]
 [0.51425692 0.39537249 0.34380736 0.20417376]
 [0.87400692 0.60221108 0.95765989 0.9857275 ]
 [0.53091832 0.70690896 0.08669885 0.55407219]]


In [88]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [89]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [92]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(5,4,2);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [93]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
***********
***********


### Problem-4: Find peaks/max in an list
- problem definition


In [101]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [102]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, A.size - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

AttributeError: 'list' object has no attribute 'size'

In [105]:
print(len(A));

10


In [103]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [ ]:
# There is a bug in the above solution. Find it...


In [104]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [ ]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


In [108]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [109]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print i 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [110]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [122]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

[3, 2, 1]

In [121]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
   if len(s) == 1:
     return [s]

   perm_list = [] # resulting list
   for a in s:
     remaining_elements = [x for x in s if x != a]
     z = permutation(remaining_elements) # permutations of sub-list

     for t in z:
       perm_list.append([a] + t)

   return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php
